## Hardcoded resource paths for web-export compatibility (DirAccess does not work in web builds).
##
## When adding new .tres resources, append their paths to the appropriate array here.
class_name ResourcePaths
extends RefCounted

const ENEMY_PATHS: Array[String] = [
	"res://resources/enemies/bat.tres",
	"res://resources/enemies/abyss_knight.tres",
	"res://resources/enemies/ancient_dragon.tres",
	"res://resources/enemies/cultist.tres",
	"res://resources/enemies/goblin.tres",
	"res://resources/enemies/kobold.tres",
	"res://resources/enemies/lich.tres",
	"res://resources/enemies/ogre_brute.tres",
	"res://resources/enemies/orc.tres",
	"res://resources/enemies/rat.tres",
	"res://resources/enemies/skeleton.tres",
	"res://resources/enemies/troll.tres",
	"res://resources/enemies/wraith.tres",
	"res://resources/enemies/zombie.tres",
	"res://resources/enemies/stone_sentry.tres",
	"res://resources/enemies/eye_acolyte.tres",
	"res://resources/enemies/clockwork_spider.tres",
	"res://resources/enemies/thorn_lasher.tres",
	"res://resources/enemies/spore_servant.tres",
	"res://resources/enemies/briar_witch.tres",
	"res://resources/enemies/ash_revenant.tres",
	"res://resources/enemies/ember_archer.tres",
	"res://resources/enemies/flame_acolyte.tres",
	"res://resources/enemies/drowned_knight.tres",
	"res://resources/enemies/harpooner.tres",
	"res://resources/enemies/abyssal_eel.tres",
	"res://resources/enemies/tidecaller.tres",
	"res://resources/enemies/mirror_duelist.tres",
	"res://resources/enemies/prism_seer.tres",
	"res://resources/enemies/shard_golem.tres",
	"res://resources/enemies/glass_dragonling.tres",
	"res://resources/enemies/void_herald.tres",
	"res://resources/enemies/deep_maw.tres",
	"res://resources/enemies/starved_godling.tres",
	# === Boss Encounter Enemies ===
	"res://resources/enemies/the_observer.tres",
	"res://resources/enemies/seraphine_thorn_saint.tres",
	"res://resources/enemies/vorrak_ashen_maw.tres",
	"res://resources/enemies/kaelros_drowned_king.tres",
	"res://resources/enemies/nyxara_mirror_witch.tres",
	# === Staff/Class Update Enemies ===
	"res://resources/enemies/frost_guardian.tres",
	"res://resources/enemies/warleader.tres",
	"res://resources/enemies/shadow_weaver.tres",
]

const ITEM_PATHS: Array[String] = [
	"res://resources/items/ascendant_elixir.tres",
	"res://resources/items/ascended_aegis.tres",
	"res://resources/items/ascended_sword.tres",
	"res://resources/items/amulet_of_guarding.tres",
	"res://resources/items/battle_axe.tres",
	"res://resources/items/bracers_of_power.tres",
	"res://resources/items/chainmail.tres",
	"res://resources/items/dagger.tres",
	"res://resources/items/celestial_greatbow.tres",
	"res://resources/items/crown_of_the_deep.tres",
	"res://resources/items/dragonbone_blade.tres",
	"res://resources/items/elixir_of_life.tres",
	"res://resources/items/elixir_of_swiftness.tres",
	"res://resources/items/elven_chain.tres",
	"res://resources/items/flail.tres",
	"res://resources/items/greater_health_potion.tres",
	"res://resources/items/greatsword.tres",
	"res://resources/items/half_plate.tres",
	"res://resources/items/hand_crossbow.tres",
	"res://resources/items/health_potion.tres",
	"res://resources/items/heavy_crossbow.tres",
	"res://resources/items/iron_axe.tres",
	"res://resources/items/leather_armor.tres",
	"res://resources/items/longbow.tres",
	"res://resources/items/longsword.tres",
	"res://resources/items/mace.tres",
	"res://resources/items/mythril_plate.tres",
	"res://resources/items/plate_armor.tres",
	"res://resources/items/phoenix_elixir.tres",
	"res://resources/items/potion_of_giant_strength.tres",
	"res://resources/items/potion_of_haste.tres",
	"res://resources/items/ring_of_accuracy.tres",
	"res://resources/items/ring_of_power.tres",
	"res://resources/items/ring_of_protection.tres",
	"res://resources/items/scale_mail.tres",
	"res://resources/items/scimitar.tres",
	"res://resources/items/scroll_fire_bolt.tres",
	"res://resources/items/scroll_lightning_bolt.tres",
	"res://resources/items/scroll_fireball.tres",
	"res://resources/items/scroll_magic_missile.tres",
	"res://resources/items/scroll_shield.tres",
	"res://resources/items/scroll_sleep.tres",
	"res://resources/items/scroll_regeneration.tres",
	"res://resources/items/shortbow.tres",
	"res://resources/items/spear.tres",
	"res://resources/items/splint_armor.tres",
	"res://resources/items/stepstone_anklet.tres",
	"res://resources/items/starfall_charm.tres",
	"res://resources/items/studded_leather.tres",
	"res://resources/items/superior_health_potion.tres",
	"res://resources/items/tonic_of_regeneration.tres",
	"res://resources/items/warhammer.tres",
	"res://resources/items/voidglass_rapier.tres",
	# === Starter / Class Weapons ===
	"res://resources/items/apprentice_staff.tres",
	"res://resources/items/hunting_bow.tres",
	"res://resources/items/training_sword.tres",
	# === Staff Ladder ===
	"res://resources/items/staff_ember.tres",
	"res://resources/items/staff_stormglass.tres",
	"res://resources/items/staff_void.tres",
	"res://resources/items/staff_astral.tres",
	"res://resources/items/staff_starfall.tres",
	"res://resources/items/staff_ascendant.tres",
	# === Class Gear ===
	"res://resources/items/vanguard_blade.tres",
	"res://resources/items/warlord_greatsword.tres",
	"res://resources/items/eaglewood_bow.tres",
	"res://resources/items/moonstring_longbow.tres",
	"res://resources/items/warriors_ring.tres",
	"res://resources/items/soldiers_plate.tres",
	"res://resources/items/deft_gloves.tres",
	"res://resources/items/scouts_cloak.tres",
	"res://resources/items/mana_circlet.tres",
	"res://resources/items/arcane_robes.tres",
	# === Gear Sets ===
	"res://resources/items/guardian_mail.tres",
	"res://resources/items/guardian_charm.tres",
	"res://resources/items/siphon_rapier.tres",
	"res://resources/items/siphon_ring.tres",
]

const TRAP_PATHS: Array[String] = [
	"res://resources/traps/alarm_trap.tres",
	"res://resources/traps/ambush_trap.tres",
	"res://resources/traps/poison_dart_trap.tres",
	"res://resources/traps/spike_trap.tres",
	"res://resources/traps/stun_trap.tres",
	"res://resources/traps/teleport_trap.tres",
]
